package com.dev.cloudsync;

import java.util.List;

public class DailyWeather {
    public List<String> time;
    public List<Integer> weather_code;
    public List<Double> temperature_2m_max;
    public List<Double> temperature_2m_min;
    public List<Double> apparent_temperature_max;
    public List<Double> apparent_temperature_min;
    public List<String> sunrise;
    public List<String> sunset;
    public List<Double> daylight_duration;
    public List<Double> sunshine_duration;
    public List<Double> uv_index_max;
    public List<Double> uv_index_clear_sky_max;
    public List<Double> rain_sum;
    public List<Double> showers_sum;
    public List<Double> snowfall_sum;
    public List<Double> precipitation_sum;
    public List<Double> precipitation_hours;
    public List<Integer> precipitation_probability_max;
    public List<Double> wind_speed_10m_max;
    public List<Double> wind_gusts_10m_max;
    public List<Integer> wind_direction_10m_dominant;
    public List<Double> shortwave_radiation_sum;
    public List<Double> et0_fao_evapotranspiration;
    public List<Double> temperature_2m_mean;
    public List<Double> apparent_temperature_mean;
    public List<Double> cape_mean;
    public List<Double> cape_max;
    public List<Double> cape_min;
    public List<Integer> cloud_cover_mean;
    public List<Integer> cloud_cover_max;
    public List<Integer> cloud_cover_min;
    public List<Double> dew_point_2m_mean;
    public List<Double> dew_point_2m_max;
    public List<Double> dew_point_2m_min;
    public List<Double> et0_fao_evapotranspiration_sum;
    public List<Object> growing_degree_days_base_0_limit_50;
    public List<Object> leaf_wetness_probability_mean;
    public List<Integer> precipitation_probability_mean;
    public List<Integer> precipitation_probability_min;
    public List<Integer> relative_humidity_2m_mean;
    public List<Integer> relative_humidity_2m_max;
    public List<Integer> relative_humidity_2m_min;
    public List<Double> snowfall_water_equivalent_sum;
    public List<Double> pressure_msl_mean;
    public List<Double> pressure_msl_max;
    public List<Double> pressure_msl_min;
    public List<Double> surface_pressure_mean;
    public List<Double> surface_pressure_max;
    public List<Double> surface_pressure_min;
    public List<Double> updraft_max;
    public List<Double> visibility_mean;
    public List<Double> visibility_min;
    public List<Double> visibility_max;
    public List<Integer> winddirection_10m_dominant;
    public List<Double> wind_gusts_10m_mean;
    public List<Double> wind_speed_10m_mean;
    public List<Double> wind_gusts_10m_min;
    public List<Double> wind_speed_10m_min;
    public List<Double> wet_bulb_temperature_2m_mean;
    public List<Double> wet_bulb_temperature_2m_max;
    public List<Double> wet_bulb_temperature_2m_min;
    public List<Double> vapour_pressure_deficit_max;
}